### ISSUE TITLE
New required task property nonFatalErrors is backwards incompatible

### ISSUE THREAD

**Issue by timlindvall** [checkupjs/checkup#1142]
1.4.0 introduced a new required task property, `nonFatalErrors`.  However, if a newer version of `@checkup/cli` runs a task relying on an older version of `@checkup/core`, the CLI errors out with the cryptic message `Cannot read message of undefined`.

To repro:
- Create a task that relies on a version of `@checkup/core` before 1.4.0.
- Run that task on a project with `@checkup/cli` 1.4.0 or later.
- Even if the task is successful without errors, the CLI will crash with the error message above.

Line where it crashes: https://github.com/checkupjs/checkup/blob/151c5c974e9b6174e142554cb0ba29224b09f898/packages/core/src/data/checkup-log-builder.ts#L118

**Comment by scalvert** [comment]
Hey @timlindvall, thanks for the issue and sorry for the unintended breakage! A quick workaround for this is the ensure you're matching the CLI version with the core version.

The `nonFatalErrors` addition was meant to be additive, but it's clear we missed a compatibility use case. I'll fix this up and publish a new version. Thanks!
