### ISSUE TITLE
`eslint-disable-task` does not handle gjs/gts files since it only runs the babel parser

### ISSUE THREAD

**Issue by chrisrng** [checkupjs/checkup#1347]
Unlike `eslint-summary-task`, `eslint-disable-task` [does not pull in your eslintrc config](https://github.com/checkupjs/checkup/blob/main/packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts#L118) so if your code is dependent on a specific preprocessor such as Ember's gts/gjs files it will fail where babel's `FlowParserMixin` throws `Unexpected token`

Ideally we can use ESLint with your eslintrc config file and expose a checkup eslint plugin with the `no-disabled-eslint` lint rule which the `eslint-disable-task` can collect.

Note for gts/gjs files [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember) already handles the `<template>` tags so you can run eslint directly

**Comment by chrisrng** [comment]
I see https://github.com/checkupjs/eslint-plugin-checkup already exists too but its empty :)

**Comment by scalvert** [comment]
What would prevent you from creating your own task that did precisely what you need? Essentially, checkup is just a structured executor of node tasks, so you should be able to create whatever you need.
