### ISSUE TITLE
Proposed change to aggregated result structure

### ISSUE THREAD

**Issue by scalvert** [checkupjs/checkup#153]
I'd like to propose a change to the aggregated result structure - the structure we ultimately end up with when we [merge task results](https://github.com/checkupjs/checkup/blob/master/packages/cli/src/commands/run.ts#L21).

First, I propose we change the categories to the following:

1. Meta - gathers meta data to be output in an unstructured format, such as project name, version, repo info, checkup version and config info, etc.
1. Insights - tasks such as dependency info, types, tests, etc.
1. Migrations - this one is obvious, migrations that are being tracked

When we process the task results, we'd 'lift' the meta tasks out to a top level `meta` bucket, leaving the remaining tasks that were categorized as either `Insights` or `Migrations` in a sibling `results` bucket. This would allow us greater control over the `meta` output, as it pertains to reporting.

Here's the proposed format:

```json
{
  "meta": {
    "project": {
      "name": "my-project",
      "version": "0.0.1",
      "repository": {
        "activeDays": "0 days",
        "age": "0 days",
        "totalCommits": 0,
        "totalFiles": 0
      }
    },
    "checkup": {
      "configHash": "9b74c9897bac770ffc029102a200c5de",
      "version": "0.0.1"
    }
  },
  "results": [
    {
      "meta": {
        "taskName": "mock-task",
        "friendlyTaskName": "Mock Task",
        "taskClassification": {
          "category": "insights",
          "priority": "medium"
        }
      },
      "result": {
        "mockTask1": 5
      }
    },
    {
      "meta": {
        "taskName": "mock-task2",
        "friendlyTaskName": "Mock Task 2",
        "taskClassification": {
          "category": "insights",
          "priority": "high"
        }
      },
      "result": {
        "mockTask2": 10
      }
    },
    {
      "meta": {
        "taskName": "mock-task3",
        "friendlyTaskName": "Mock Task 3",
        "taskClassification": {
          "category": "insights",
          "priority": "low"
        }
      },
      "result": {
        "mockTask2": 10
      }
    },
    {
      "meta": {
        "taskName": "mock-task4",
        "friendlyTaskName": "Mock Task 4",
        "taskClassification": {
          "category": "migrations",
          "priority": "low"
        }
      },
      "result": {
        "mockTask2": 10
      }
    }
  ]
}

```

We need to figure out a generic way to output the meta data in a nice way for reporting, but it shouldn't be too complicated.

Please comment with your thoughts.

**Comment by rwjblue** [comment]
IMHO, this refactor nicely decouples the reporting infrastructure input from the output / gathering infrastructure.

**Comment by scalvert** [comment]
I think part of this change is recognizing that the `meta` data is likely default tasks. We need to change the way tasks are executed so that we execute this type of meta data collection _all the time_. I'm preparing a PR that does just that - moves `plugin-default` back into the `cli` package, and creates the notion of default tasks that are run regardless. This data will form the basis for the project information displayed at the top of the report.

**Comment by scalvert** [comment]
Resolved via the above two PRs.
