### ISSUE TITLE
Config generation workflow issues

### ISSUE THREAD

**Issue by lbdm44** [checkupjs/checkup#211]
Following the setup process defined at https://github.com/checkupjs/checkup/blob/master/packages/cli/README.md it notes to generate a config file via running

```sh-session
$ checkup generate config
```

However that produces an error
<img width="1213" alt="Screen Shot 2020-04-06 at 4 57 11 PM" src="https://user-images.githubusercontent.com/702906/78616828-446a5400-782a-11ea-8b91-06595f2d986e.png">

So I did this instead:

```sh-session
$ checkup generate config.js
```

Following the prompts, I selected `Ember` and `JSON` yet the resulting file is `.checkuprc` which does not match any of the options that I chose when generating the file.

I would like to see the docs be updated to match the correct syntax for file generation (or the file generation to be fixed to match the docs) and then the resulting file to match the options passed `.checkuprc.json` in this case or `.checkuprc.js` if I chose JS or `.checkuprc.toml` if I choose TOML

**Comment by scalvert** [comment]
I wasn't able to specifically reproduce this. I did, however, find some other issues with the config generator. I've address them in #280

**Comment by scalvert** [comment]
Going to close this for now, @lbdm44. Feel free to reopen if issues persist.
