### ISSUE TITLE
Idea: new generator command

### ISSUE THREAD

**Issue by scalvert** [checkupjs/checkup#297]
Adding a new checkup plugin to configuration can be handled via generators.

```shell
$ checkup config:add plugin checkup-plugin-ember
```

This would do the following:
1. Add the `checkup-plugin-ember` entry to the `plugins` array in the config
1. Add the `checkup-plugin-ember` package to the package.json's devDependencies
1. Run yarn/npm install

**Comment by carakessler** [comment]
@scalvert do you think this is necessary for v1.0.0?

**Comment by scalvert** [comment]
No. I think this can wait.

**Comment by scalvert** [comment]
Going to close this for now, as I think it's unnecessary.
