### ISSUE TITLE
[enhancement] ember-template-lint additional types

### ISSUE THREAD

**Issue by gabrielcsapo** [checkupjs/checkup#514]
I am trying to add a local plugin for ember-template lint that looks something like the following;

```js
const TEMPLATE_LINT_CONFIG: TemplateLintConfig = {
  plugins: [
    {
      name: 'local-rules',
      rules: {
        'hello-world': require(path.resolve(__dirname, '../../template-lint-rules/hello-world')),
      },
    },
  ],
  rules: {
    'hello-world': 'error'
  },
};
```

Looking at the types for ember-template-lint config it looks like it is missing some fields.

https://github.com/checkupjs/checkup/blob/9fe60a9f02ef9d9ef1d68b2f4be479e4d52aa15e/packages/core/src/types/ember-template-lint.ts#L29-L33

ember-template-lint doesn't expose types you can see the top level properties that are allowed here:

https://github.com/ember-template-lint/ember-template-lint/blob/b7195d0b6ae8051aff904a49bf9969741cfbf877/lib/get-config.js#L119-L126

> I am using @checkup/core@0.1.1

**Comment by scalvert** [comment]
We can absolutely extend the types. Ideally these types will be defined in `ember-template-lint` itself, but we can for sure add our own in the interim.
