### ISSUE TITLE
[feature] more stack info when error is thrown

### ISSUE THREAD

**Issue by gabrielcsapo** [checkupjs/checkup#522]
*Motivation*

When an error is thrown in a checkup task the resulting output is the following;

<img width="345" alt="Screen Shot 2020-06-29 at 10 39 50 AM" src="https://user-images.githubusercontent.com/1854811/86038332-9c61c280-b9f5-11ea-8316-b0ef3b87f9c5.png">

It would be great to see additional stack information about where the error is coming from or a full stack that can be referenced in an external file.

**Comment by scalvert** [comment]
We did some work to intentionally not error on tasks when tasks generate errors. We could absolutely extend the error capturing functionality to include the thrown error.
