### ISSUE TITLE
[question] is there a way to run multiple tasks?

### ISSUE THREAD

**Issue by gabrielcsapo** [checkupjs/checkup#525]
*Motivation*

I am looking to run a select group of tasks. 

When I run `checkup --task foo --task bar --task moo` this does not result in multiple tasks, just only moo. Would there be a way to run `checkup --tasks 'foo, bar, moo'` ?

**Comment by scalvert** [comment]
Thanks, @gabrielcsapo. Currently there isn't a way to run multiple. We can pretty easily extend this to allow multiples to be run though. I'll add it to the backlog.

**Comment by carakessler** [comment]
@gabrielcsapo I will be doing this today/tomorrow, will hit you up when it is done!
