### ISSUE TITLE
[feature] default color scheme

### ISSUE THREAD

**Issue by gabrielcsapo** [checkupjs/checkup#530]
*Motivation*

I have a few tasks I am working on and find myself using the same colors for bar and sectionedBar, it would be great if there was a default color scheme to keep all plugins looking cohesive.

**Comment by scalvert** [comment]
I've implemented a randomized theme using a range of ansi256 colors. Let me know if this works for you.

Example of Octane migration task:

<img width="673" alt="Screen Shot 2020-08-05 at 7 42 43 AM" src="https://user-images.githubusercontent.com/180990/89429549-8b8e2600-d6f2-11ea-9b4b-64b94747d71e.png">

**Comment by gabrielcsapo** [comment]
That's great! Would this trickle down to the UI components in a particular task? Do we need to specify colors for bar and segmentedBar?

**Comment by scalvert** [comment]
It's all automatic now. The colors are variable though, and merely serve to provide visual distinction between things on the screen.
