### ISSUE TITLE
[enhancement] use Number.prototype.toLocaleString() for bar and sectionedBar

### ISSUE THREAD

**Issue by gabrielcsapo** [checkupjs/checkup#531]
*Motivation*

<img width="480" alt="Screen Shot 2020-07-01 at 3 32 01 PM" src="https://user-images.githubusercontent.com/1854811/86298386-7a616f00-bbb2-11ea-85ab-f30ee693a803.png">

I am using the sectionedBar and it is hard to distinguish large numbers, it would be great to use toLocaleString when rendering the bar data.

**Comment by scalvert** [comment]
PRs welcome, and encouraged!
