### ISSUE TITLE
Octane task fails on unnamed classic class extensions

### ISSUE THREAD

**Issue by chriskrycho** [checkupjs/checkup#568]
If you have code like this in your codebase:

```js
this.owner.register(
  'service:some-service',
  Service.extend({
    someProp: 'alas',
  })
);
```

then the Octane Checkup task will fail like this:

| Taskname                | Error                                    |
| ----------------------- | ---------------------------------------- |
| octane-migration-status | Cannot read property 'name' of undefined |

**Comment by chriskrycho** [comment]
Note: I am poking at the details and will likely have a PR up tomorrow (if no one beats me to it); it looks like it's just a function of the lint rule expecting the `.extend` item to be *named*? If someone has a quick pointer to the location of the issue, I'm happy to fix; otherwise I'll dig down till I find it!

**Comment by chriskrycho** [comment]
My guess is *no*. I got pulled away into something else and was unable to poke further a couple weeks ago, but my assumption is that the lint rule itself fails here.

**Comment by scalvert** [comment]
Any chance you were able to look into this, @chriskrycho?

**Comment by chriskrycho** [comment]
Unfortunately, no. Buried in some other work. Will follow up with you once I clear some other stuff I'm neck deep in.

**Comment by scalvert** [comment]
No problem. I can take a look also.

**Comment by carakessler** [comment]
It is the rule `no-actions-hash`, `Cannot read property 'name' of undefined` 

This is what is triggering the error 
```        
Service.extend(Evented, {
   ...this.badge,
   getBadgeCount: this.sandbox.stub().returns(4),
})
```

If you kill the spread operator before `this.badge`, it works. I am going to open an issue in `eslint-plugin-ember`

**Comment by carakessler** [comment]
https://github.com/ember-cli/eslint-plugin-ember/issues/921
