### ISSUE TITLE
[question] analyzedFilesCount schema meaning

### ISSUE THREAD

**Issue by gabrielcsapo** [checkupjs/checkup#634]
There is an attribute in the schema `analyzedFilesCount` which is an array of files not a count as the name would suggest.

Is there a way we can change this name to `analyzedFiles`?

**Comment by scalvert** [comment]
Yes, we should definitely do this. I propose the following:

1. We keep `analyzedFilesCount`, but populate it with the length of `analyzedFiles`
1. We add `analyzedFiles`, who's data is the current `analyzedFilesCount`.
