### ISSUE TITLE
Create system for auto-generating documentation.

### ISSUE THREAD

**Issue by scalvert** [checkupjs/checkup#734]
We need to provide a system similar to what `eslint` does, which would include the following:

1. Documentation for tasks
  - description
  - sample output
  - task config option definitions
2. A way to auto-generate the documentation
3. A way to auto generate docs for plugins
  - listing tasks with links to task documentation
  - grouping by category and group

**Comment by ttbach** [comment]
I can take this on!

**Comment by carakessler** [comment]
Awesome @ttbach! 

To add a little color to what @scalvert posted above, what we are looking for for the MVP is mostly focused around Task documentation. Similar to eslint, each Task and plugin should have a (required) markdown file associated with it, that explains what it is doing, provides examples for what its looking for, etc. 

To break this down a bit more: 

**Tasks**
1) When a new Task is generated, we should also be generating a `.md` file by the same name, to serve as its documentation. 
2) We need to create a template for the Task documentation - some of this will be autogenerated some will be manual (more can become automatic as feature enhancements down the line)
3) We need to add a required `description` field to all Tasks, which will live in the Task itself, but should be automatically brought into the documentation file. 
4) Task documentation should pull in the `actions` associated with it

**Plugins**
5) When a new plugin is generated, we should be also generating a `.md` file (we maybe already gen a README?). Worth discussing whether this documentation should live in a README or a different file (would love thoughts @scalvert). At the very least, the plugin documentation file should contain a list of all the Tasks in the plugin (grouped appropriately), and links to their respective documentations.

**Documentation Infrastructure**
6) There needs to be a precommit hook that goes through and updates and populates documentation based on changes. 
7) This functionality needs to be encapsulated appropriately such that external plugins can also leverage it.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Happy to chat next week to help you get started on this, and ramped up generally on these different constructs!

**Comment by ttbach** [comment]
Thanks for the extra details. I'll take a look at this and put something on your calendar to sync up next week!
