### ISSUE TITLE
Pull out dependency on oclif 

### ISSUE THREAD

**Issue by carakessler** [checkupjs/checkup#866]
Checkup seems to have outgrown oclif, and its gotten to the point where it is causing more problems than it is solving, particularly when it comes to the flexibility of the node API. 

We need to remove our dependency on oclif, and build out the hooks, config, command, error, and flags infrastructure ourselves. 

- [x] Create parallel `checkup` bin script
- [x] Create top level command, sub commands (`run` and `validate`)
- [x] Parse arguments and ensure correct usage output
- [x] Decouple command classes from oclif
- [x] Implement plugin loading

**Comment by scalvert** [comment]
Implemented in #900
